Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # Copy credentials file
  config.vm.provision "file", source: "../credentials.txt", destination: "/home/vagrant/credentials.txt"
  # Provision
  config.vm.provision :shell, path: "provisioning.sh"
end
